inherit_from: .rubocop_rails.yml

Style/FileName:
  Exclude:
    - 'bin/codeclimate-rubocop'

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
