default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
development:
  <<: *default
  database: client_enrollment_development
  username: postgres
  password: postgres
test:
  <<: *default
  database: client_enrollment_test
  username: postgres
  password: postgres
production:
  <<: *default
  database: client_enrollment_production
  username: client_enrollment
  password: <%= ENV['CLIENT_ENROLLMENT_DATABASE_PASSWORD'] %>
